### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tspaanan** [EternalAzure/ot-harjoitustyo#5]
testattu versio: viikko5 Release, Linux build

Tarkastelin ensisijaisesti sekä zip-pakattua lähdekoodia että kokeilin käyttää jar-pakettia.

Ennen koodin lukemista tutustuin vaatimusmäärittelyyn ja arkkitehtuurikuvaukseen. Jälkimmäinen oli aivan omaa luokkaansa yleisessä mahtavuudessaan, ja tämän arkkitehtuurikuvauksen lukemisen jälkeen itse koodin lukeminen oli varsin suoraviivaista. Kun arkkitehtuurikuvaus oli ensin tarjonnut kattavan yleiskatsauksen koodin rakenteeseen, ja itse koodi oli jaoteltu pakkauksiin, luokkiin ja metodeihin esimerkillisesti sekä nimetty kuvaavasti, sitä oli ilo lukea. Sain itselleni hyviä vinkkejä siihen, miten asioita kannattaa toteuttaa. Esimerkiksi sellaiset yksityiskohdat, kuten omat luokat AlertWindow ja ConfirmWindow, joita voi käyttää näppärästi vaihtuvien viestien välittämiseen käyttäjälle, jatkuvasti toistuva käyttäjän syötteen validointi sekä usein toistuvien error-viestien asettaminen muuttujiin ovat kaikki sellaisia asioita, joiden käytöllä omakin koodini paranee.

Käyttäjän syötteen validoiminen on koodissa paikallaan, mutta aina itse validointi ei vaikuta olevan riittävän kattavaa. Esimerkiksi HubController-luokan addRoom-metodi tarkistaa lopulta vain sen, että käyttäjä on syöttänyt jotain huoneen nimelle varattuun tekstikenttään. Kun tämä yhdistetään siihen, ettei SQL-komentoja parametrisoida, on käyttäjän mahdollista ohjata tietokannan toimintaa sopivilla syötteillä. Tietokanta on (käsittääkseni) esimerkiksi mahdollista rikkoa antamalla uuden huoneen nimeksi merkkijono "',NULL); DROP TABLE rooms;". Ongelman voi välttää joko estämällä tietyt erikoismerkit, kuten pilkut ja puolipisteet, huoneiden nimissä tai vielä paremmin välttämällä asettamasta käyttäjän syöte suoraan osaksi SQL-komentoa. addRoom-metodin kaksi viimeistä riviä voidaan korvata seuraavilla kolmella:
```
PreparedStatement sql = yhteysTietokantaan.prepareStatement("INSERT INTO rooms (room, temperature) VALUES (?, NULLIF('" + temperature + "', ''))");
sql.setString(1, name);
return executeSQL(sql, "'" + name + "' already exists");
```
Muutos toki vaatii (ymmärtääkseni) myös sen muutoksen, että pelkän Statement-olion sijaan parametrina välitetään myös joko PreparedStatement-olio tai sitten yhteys tietokantaan (kuten yllä muuttujassa 'yhteysTietokantaan'). temperature-muuttujaan tallennettu tieto voidaan puolestaan helposti validoida kokonaisluvuksi, jonka jälkeen sen liittämisessä ei pitäisi olla ongelmaa. Toinen huomiota kiinnittänyt SQL-yksityiskohta oli sisäänkirjautumisen yhteydessä käyttäjänimen käyttö LIKE-operaattorin osana. Jar-pakattua ohjelmaa käyttäessä tämä tarkoittikin, että samalla salasanalla sisäänpääsivät Anita, anita, a% ja pelkkä %.

Tätä SQL-parametrisoinnin puutetta lukuun ottamatta kaikki muu koodi oli kuitenkin nähdäkseni erittäin pätevästi kirjoitettua ja kurssilla käytettyjen koodin laatuvaatimusten mukaista. Toinen isompi muutosehdotus koskeekin vain sen rakenteen yksityiskohtia. Isossa mittakaavassa luokat ovat kaikki paikallaan, mutta kiinnitin huomiota siihen, että tietokannan käyttö tapahtui paljon sitä varten tarkoitetun dao-paketin ulkopuolella. Jakaisin koodia uudestaan seuraavalla tavalla:

Utils-luokka on kokoelma kahdenlaisia metodeja: SQL-kyselyjä ja validointia. Pilkkoisin nämä erilleen (SQLquories.java ja Validation.java), ja siirtäisin muista luokista vastaavat metodit näiden sisään (mm. HubController-luokan sisältämät SQL-kyselyt). Validation-luokka jäisi luontevasti logic-pakettiin, SQLquories taas siirtyisi osaksi dao-pakettia. Myös esim. logic-paketin sisältämä ServerConnection kuuluisi luontevasti dao-paketin osaksi.

Pari pikku juttua vielä: skipped_files.xml sisältämä URL puppycrawl.com -sivustolle on kuollut linkki. Lisäksi pom.xml ilmeisesti ohjeistaa kääntäjän käyttämään Javan versiota 8, kun sen pitäisi olla 11.

Kokeilin myös zip-pakatun lähdekoodin kääntämistä ja testien ajamista. Lähdekoodin kääntäminen ei onnistunut suoraan Readme-tiedoston ohjeilla, mutta -Dexec.mainClass=fi.orderly.ui.Login lisämääreellä kääntäminen onnistui. Ohjelma ei edes kaatunut, vaikka minkäänlaista yhteyttä mihinkään tietokantaan ei ollut! Yksikkötestien ajaminen sen sijaan kaatui aina virheeseen: "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project Orderly: There are test failures." Yksikkötestien koodi itsessään oli kuitenkin jälleen pätevän näköistä ja testasi oikeita asioita.

Kaikkiaan dokumentaatio ja koodi on siis erinomaisella tolalla, ja mahdollisen refaktoroinnin ja SQL-kyselyjen parametrisoinnin lisäksi siinä ei ollut huomauttamisen sijaa.

**Comment by EternalAzure** [comment]
Kiitos palautteesta. Siitä oli huomattavasti apua. Luin sen monta kertaa uudelleen, koska siitä tuli niin hyvä mieli :D
Javassa on sisään rakennettu Alert-luokka jolla saa super kätevästi ilmoitettua virheviestit käyttäjälle. Minä tein omat alert ja confirm koska minun sovelluksessa on tietty estetiikka
